apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zone-cert
spec:
  secretName: zone-tls-secret
  issuerRef:
    name: zone-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - zone.dev
