kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jetstream-volume-claim
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
