apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: payments-pg-volume-claim
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
