apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: "/Users/shreyas/zone/redis"
